services:
  db:
    image: postgres:13.10
    env_file: .env
    volumes:
      - pg_data:/var/lib/postgresql/data
    networks:
      - kittygram_net
    restart: always

  backend:
    image: pavellchemakin/kittygram_backend:latest
    env_file: .env
    volumes:
      - static:/backend_static
      - media:/media
    networks:
      - kittygram_net
    depends_on:
      - db
    restart: always

  frontend:
    image: pavellchemakin/kittygram_frontend:latest
    env_file: .env
    volumes:
      - static:/static
    networks:
      - kittygram_net
    restart: always

  gateway:
    image: pavellchemakin/kittygram_gateway:latest
    env_file: .env
    volumes:
      - static:/static
      - media:/media
    ports:
      - "127.0.0.1:9000:80"
    networks:
      - kittygram_net
    depends_on:
      - backend
      - frontend
    restart: always

volumes:
  pg_data:
  static:
  media:

networks:
  kittygram_net:
