name: Main Kittygram workflow
on:
  push:
    branches:
      - main
concurrency:
  group: deploy-${{ github.ref }}
  cancel-in-progress: true
env:
  CLEAN_DB: "false"
jobs:
  tests:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:13.10
        env:
          POSTGRES_DB: kittygram
          POSTGRES_USER: kittygram_user
          POSTGRES_PASSWORD: kittygram_password
        ports:
          - 5432:5432
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.9
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8==6.0.0 flake8-isort==6.0.0
          pip install -r ./backend/requirements.txt
      - name: Test with flake8 and django tests
        env:
          POSTGRES_DB: kittygram
          POSTGRES_USER: kittygram_user
          POSTGRES_PASSWORD: kittygram_password
          DB_HOST: 127.0.0.1
          DB_PORT: 5432
        run: |
          python -m flake8 backend/
          cd backend/
          python manage.py test

  build_and_push_to_docker_hub:
    runs-on: ubuntu-latest
    needs: tests
    steps:
      - uses: actions/checkout@v3
      - uses: docker/setup-buildx-action@v2
      - uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - uses: docker/build-push-action@v4
        with:
          context: ./backend/
          push: true
          tags: pavellchemakin/kittygram_backend:latest

  frontend_tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - run: |
          cd frontend/
          npm ci
      - run: |
          cd frontend/
          npm run test

  build_frontend_and_push_to_docker_hub:
    runs-on: ubuntu-latest
    needs: frontend_tests
    steps:
      - uses: actions/checkout@v3
      - uses: docker/setup-buildx-action@v2
      - uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - uses: docker/build-push-action@v4
        with:
          context: ./frontend/
          push: true
          tags: pavellchemakin/kittygram_frontend:latest

  build_gateway_and_push_to_docker_hub:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: docker/setup-buildx-action@v2
      - uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - uses: docker/build-push-action@v4
        with:
          context: ./nginx/
          push: true
          tags: pavellchemakin/kittygram_gateway:latest

  deploy:
    runs-on: ubuntu-latest
    needs:
      - build_and_push_to_docker_hub
      - build_frontend_and_push_to_docker_hub
      - build_gateway_and_push_to_docker_hub
    steps:
      - uses: actions/checkout@v3

      - name: Copy docker-compose.yml via ssh
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USER }}
          key: ${{ secrets.SSH_KEY }}
          passphrase: ${{ secrets.SSH_PASSPHRASE }}
          source: "docker-compose.production.yml"
          target: "kittygram"

      - name: Executing remote ssh commands to deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USER }}
          key: ${{ secrets.SSH_KEY }}
          passphrase: ${{ secrets.SSH_PASSPHRASE }}
          script: |
            set -euxo pipefail
            cd ~/kittygram

            sudo docker compose -f docker-compose.production.yml pull
            sudo docker compose -f docker-compose.production.yml down -v --remove-orphans -t 30 || true

            sudo fuser -k 9000/tcp || true

            sudo docker system prune -af --volumes || true
            sudo docker volume rm kittygram_static kittygram_media || true
            if [ "${CLEAN_DB}" = "true" ]; then sudo docker volume rm kittygram_pg_data || true; fi

            sudo systemctl restart docker

            sudo docker compose -f docker-compose.production.yml up -d --force-recreate --remove-orphans

            sudo docker compose -f docker-compose.production.yml exec -T db bash -lc 'until pg_isready -U "$POSTGRES_USER" -d "$POSTGRES_DB" -h 127.0.0.1 -p 5432; do sleep 1; done'

            sudo docker compose -f docker-compose.production.yml exec -T backend python manage.py migrate
            sudo docker compose -f docker-compose.production.yml exec -T backend python manage.py collectstatic --noinput
            sudo docker compose -f docker-compose.production.yml exec -T backend bash -lc 'rm -rf /backend_static/static/* && cp -r /app/collected_static/. /backend_static/static/'

  send_message:
    runs-on: ubuntu-latest
    needs: deploy
    steps:
      - uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_TO }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          message: Деплой успешно выполнен!
